language: node_js
node_js:
  - "11"
before_install:
  - sudo apt-get update
cache: npm
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - npm i
script:
  - git checkout -b new_website_content
  - node .
  - git add docs/
  - git commit -m "Generate content of website by Hugo with TravisCI"
  - git push origin new_website_content
